condominios = [
    {"nome": "ÁGAPE", "id": "190", "SIGLA": "AP"},
    {"nome": "ALEXANDRITA", "id": "189", "SIGLA": "AX"},
    {"nome": "ALMERE", "id": "217", "SIGLA": "ALM"},
    {"nome": "ALVORADA", "id": "147", "SIGLA": "ALV"},
    {"nome": "ANA LAURA III", "id": "206", "SIGLA": "AL III"},
    {"nome": "ANGELINA ALVES", "id": "41", "SIGLA": "AA"},
    {"nome": "ANTÔNIO PARREIRA", "id": "222", "SIGLA": "ANP"},
    {"nome": "ARAÚJO", "id": "117", "SIGLA": "AJ"},
    {"nome": "ATACAMA", "id": "247", "SIGLA": "AT"},
    {"nome": "AYRTON SENNA 1", "id": "52", "SIGLA": "AS"},
    {"nome": "AYRTON SENNA 2", "id": "228", "SIGLA": "AY"},
    {"nome": "AZALÉA", "id": "238", "SIGLA": "AZA"},
    {"nome": "BARROS", "id": "210", "SIGLA": "BA"},
    {"nome": "BETEL", "id": "284", "SIGLA": "BTL"},
    {"nome": "BRILHANTE 1", "id": "167", "SIGLA": "BRI"},
    {"nome": "CASTRO ALVES 2", "id": "283", "SIGLA": "CSA"},
    {"nome": "CONTINENTAL", "id": "161", "SIGLA": "CO"},
    {"nome": "CRISTAL", "id": "29", "SIGLA": "CR"},
    {"nome": "DE PAULA IV", "id": "251", "SIGLA": "DP"},
    {"nome": "DE PAULA V", "id": "256", "SIGLA": "DPV"},
    {"nome": "DORNELES", "id": "255", "SIGLA": "DO"},
    {"nome": "EFIGÊNIA GUSMÃO", "id": "298", "SIGLA": "EG"},
    {"nome": "ELEUTÉRIO", "id": "179", "SIGLA": "ET"},
    {"nome": "EMANUEL", "id": "232", "SIGLA": "EMA"},
    {"nome": "ESCARPAS DO LAGO", "id": "243", "SIGLA": "ELA"},
    {"nome": "ESMERALDA 2", "id": "211", "SIGLA": "ESM"},
    {"nome": "EVOLUTION II", "id": "121", "SIGLA": "EV"},
    {"nome": "FÊNIX", "id": "235", "SIGLA": "FE"},
    {"nome": "FELYPE HENRIQUES", "id": "204", "SIGLA": "FH"},
    {"nome": "FILADÉLFIA", "id": "261", "SIGLA": "FI"},
    {"nome": "FLAMBOYAN", "id": "185", "SIGLA": "FLA"},
    {"nome": "FLORENÇA 4", "id": "263", "SIGLA": "FLN"},
    {"nome": "GALDINO GOMES", "id": "258", "SIGLA": "GG"},
    {"nome": "GERASA 2", "id": "62", "SIGLA": "GE"},
    {"nome": "HORTO PALACE", "id": "230", "SIGLA": "HP"},
    {"nome": "IGOR VICTOR", "id": "234", "SIGLA": "IV"},
    {"nome": "ILÁRIA FERREIRA", "id": "212", "SIGLA": "IF"},
    {"nome": "IPANEMA", "id": "285", "SIGLA": "IP"},
    {"nome": "ITAPARICA", "id": "296", "SIGLA": "ITA"},
    {"nome": "J34-D2", "id": "223", "SIGLA": "J34D2"},
    {"nome": "JACARANDÁ", "id": "207", "SIGLA": "JC"},
    {"nome": "JASPE", "id": "168", "SIGLA": "JP"},
    {"nome": "JATOBÁ 2", "id": "213", "SIGLA": "JB"},
    {"nome": "JO-11", "id": "281", "SIGLA": "JO11"},
    {"nome": "JOSÉ OLÍMPIO", "id": "203", "SIGLA": "JO"},
    {"nome": "JUDITH DE MELLO", "id": "69", "SIGLA": "JM"},
    {"nome": "KALLEB", "id": "182", "SIGLA": "KL"},
    {"nome": "LENDHER", "id": "286", "SIGLA": "LE"},
    {"nome": "LETÍCIA", "id": "299", "SIGLA": "LET"},
    {"nome": "LIBERTAS I", "id": "231", "SIGLA": "LI"},
    {"nome": "MALBOROUGH", "id": "266", "SIGLA": "MBR"},
    {"nome": "MALTA", "id": "226", "SIGLA": "MAT"},
    {"nome": "MARCELLE", "id": "201", "SIGLA": "MAR"},
    {"nome": "MÁRIO DE ANDRADE II", "id": "289", "SIGLA": "MAD"},
    {"nome": "MAURA MIRANDA", "id": "227", "SIGLA": "MIA"},
    {"nome": "MORIÁ 2", "id": "180", "SIGLA": "MRA"},
    {"nome": "NOÉLIA", "id": "245", "SIGLA": "NO"},
    {"nome": "NOVAES", "id": "248", "SIGLA": "NV"},
    {"nome": "ORQUÍDEA", "id": "187", "SIGLA": "OQ"},
    {"nome": "OSWALDO DE ANDRADE", "id": "202", "SIGLA": "OS"},
    {"nome": "PAULINA", "id": "291", "SIGLA": "PLN"},
    {"nome": "PEDRO I", "id": "250", "SIGLA": "PE"},
    {"nome": "POÇOS DE CALDAS", "id": "176", "SIGLA": "POC"},
    {"nome": "PONTAL DA JACARAÍPE", "id": "184", "SIGLA": "PJ"},
    {"nome": "PRIME", "id": "293", "SIGLA": "PRI"},
    {"nome": "RIBEIRO DE SÁ", "id": "295", "SIGLA": "RS"},
    {"nome": "RODAR", "id": "186", "SIGLA": "RD"},
    {"nome": "SAFIRA 2", "id": "288", "SIGLA": "SAF"},
    {"nome": "SANTANA", "id": "253", "SIGLA": "STN"},
    {"nome": "SANTO ELÓI", "id": "249", "SIGLA": "SE"},
    {"nome": "SHALOM", "id": "244", "SIGLA": "SHA"},
    {"nome": "SIDÔNIA", "id": "163", "SIGLA": "SDN"},
    {"nome": "SILMOR", "id": "262", "SIGLA": "SI"},
    {"nome": "SIMAN", "id": "279", "SIGLA": "SIM"},
    {"nome": "SOARES", "id": "205", "SIGLA": "SOA"},
    {"nome": "SOLAR RESIDENCIAL", "id": "239", "SIGLA": "SR"},
    {"nome": "TERESINHA SENA", "id": "240", "SIGLA": "TS"},
    {"nome": "VALPARAÍSO", "id": "224", "SIGLA": "VA"},
    {"nome": "VERONA 1", "id": "259", "SIGLA": "VE"},
    {"nome": "VERONA 2", "id": "265", "SIGLA": "VRN"},
    {"nome": "VILAGE WHITE", "id": "79", "SIGLA": "VW"},
    {"nome": "VISINTIN", "id": "143", "SIGLA": "VS"},
    {"nome": "VISTA DA MATA", "id": "218", "SIGLA": "VM"},
    {"nome": "VISTA LINDA II", "id": "294", "SIGLA": "VL"},
    {"nome": "ZAGNOLI", "id": "257", "SIGLA": "ZA"},
    {"nome": "ZULMIRA XAVIER", "id": "260", "SIGLA": "ZX"},
    {"nome": "MIRANDA", "id": "20", "SIGLA": "MR"},
]
